[package]
name = "hahabot"
version = "0.1.0"
authors = ["Alex Bush <swapoff@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "*"
env_logger = "*"
log = "*"
rand = "0.5.5"
reqwest = "0.9.11"
select = "*"
tokio = { version = "0.2", features = ["macros"] }
carapax = "0.4.0"
rusqlite = "0.21.0"
time = "0.1.0"
htmlescape = "0.3.1"
